/**
 * KHO NGỮ LIỆU SEED TỰ CHỦ (AUTONOMOUS STANDALONE SEED LEXICON)
 * Đảm bảo các Worker Crawlers trên GitHub Actions hoạt động 24/7 độc lập,
 * không bao giờ bị dừng do thiếu dữ liệu hoặc mất kết nối cơ sở dữ liệu.
 */

export interface JapaneseWordSeed {
  front: string;
  reading: string;
  meaning: string;
  category: string;
}

export const SEED_JAPANESE_WORDS: JapaneseWordSeed[] = [
  // Đời sống hàng ngày & Gia đình
  { front: '家族', reading: 'かぞく', meaning: 'Gia đình', category: 'family' },
  { front: '両親', reading: 'りょうしん', meaning: 'Bố mẹ', category: 'family' },
  { front: '父', reading: 'ちち', meaning: 'Bố mình', category: 'family' },
  { front: '母', reading: 'はは', meaning: 'Mẹ mình', category: 'family' },
  { front: '兄', reading: 'あに', meaning: 'Anh trai mình', category: 'family' },
  { front: '姉', reading: 'あね', meaning: 'Chị gái mình', category: 'family' },
  { front: '弟', reading: 'おとうと', meaning: 'Em trai mình', category: 'family' },
  { front: '妹', reading: 'いもうと', meaning: 'Em gái mình', category: 'family' },
  { front: '子供', reading: 'こども', meaning: 'Trẻ em, con cái', category: 'family' },
  { front: '友達', reading: 'ともだち', meaning: 'Bạn bè', category: 'social' },
  { front: '先生', reading: 'せんせい', meaning: 'Giáo viên, bác sĩ', category: 'education' },
  { front: '学生', reading: 'がくせい', meaning: 'Học sinh, sinh viên', category: 'education' },
  { front: '医者', reading: 'いしゃ', meaning: 'Bác sĩ', category: 'medical' },
  { front: '会社員', reading: 'かいしゃいん', meaning: 'Nhân viên công ty', category: 'work' },
  { front: '銀行員', reading: 'ぎんこういん', meaning: 'Nhân viên ngân hàng', category: 'work' },
  { front: '研究者', reading: 'けんきゅうしゃ', meaning: 'Nhà nghiên cứu', category: 'education' },

  // Trường học, Văn phòng & Đồ vật
  { front: '学校', reading: 'がっこう', meaning: 'Trường học', category: 'education' },
  { front: '大学', reading: 'だいがく', meaning: 'Trường đại học', category: 'education' },
  { front: '教室', reading: 'きょうしつ', meaning: 'Phòng học', category: 'education' },
  { front: '図書館', reading: 'としょかん', meaning: 'Thư viện', category: 'places' },
  { front: '本', reading: 'ほん', meaning: 'Quyển sách', category: 'objects' },
  { front: '辞書', reading: 'じしょ', meaning: 'Từ điển', category: 'objects' },
  { front: 'ノート', reading: 'のーと', meaning: 'Vở ghi chép', category: 'objects' },
  { front: '手帳', reading: 'てちょう', meaning: 'Sổ tay cá nhân', category: 'objects' },
  { front: '時計', reading: 'とけい', meaning: 'Đồng hồ', category: 'objects' },
  { front: '傘', reading: 'かさ', meaning: 'Chiếc ô', category: 'objects' },
  { front: '鞄', reading: 'かばん', meaning: 'Cặp sách, túi xách', category: 'objects' },
  { front: '鍵', reading: 'かぎ', meaning: 'Chìa khóa', category: 'objects' },
  { front: '机', reading: 'つくえ', meaning: 'Cái bàn học', category: 'furniture' },
  { front: '椅子', reading: 'いす', meaning: 'Cái ghế', category: 'furniture' },
  { front: '部屋', reading: 'へや', meaning: 'Căn phòng', category: 'places' },
  { front: '窓', reading: 'まど', meaning: 'Cửa sổ', category: 'places' },
  { front: 'ドア', reading: 'どあ', meaning: 'Cửa ra vào', category: 'places' },

  // Đồ ăn, Thức uống & Ẩm thực Nhật Bản
  { front: 'ご飯', reading: 'ごはん', meaning: 'Cơm, bữa ăn', category: 'food' },
  { front: '朝ご飯', reading: 'あさごはん', meaning: 'Bữa sáng', category: 'food' },
  { front: '昼ご飯', reading: 'ひるごはん', meaning: 'Bữa trưa', category: 'food' },
  { front: '晩ご飯', reading: 'ばんごはん', meaning: 'Bữa tối', category: 'food' },
  { front: 'パン', reading: 'ぱん', meaning: 'Bánh mì', category: 'food' },
  { front: '卵', reading: 'たまご', meaning: 'Quả trứng', category: 'food' },
  { front: '肉', reading: 'にく', meaning: 'Thịt', category: 'food' },
  { front: '魚', reading: 'さかな', meaning: 'Con cá', category: 'food' },
  { front: '野菜', reading: 'やさい', meaning: 'Rau củ', category: 'food' },
  { front: '果物', reading: 'くだもの', meaning: 'Trái cây', category: 'food' },
  { front: '水', reading: 'みず', meaning: 'Nước lọc', category: 'drink' },
  { front: 'お茶', reading: 'おちゃ', meaning: 'Trà xanh Nhật Bản', category: 'drink' },
  { front: '紅茶', reading: 'こうちゃ', meaning: 'Hồng trà', category: 'drink' },
  { front: '牛乳', reading: 'ぎゅうにゅう', meaning: 'Sữa bò tươi', category: 'drink' },
  { front: '酒', reading: 'さけ', meaning: 'Rượu sake', category: 'drink' },
  { front: 'ビール', reading: 'びーる', meaning: 'Bia', category: 'drink' },
  { front: '寿司', reading: 'すし', meaning: 'Món sushi', category: 'food' },
  { front: 'ラーメン', reading: 'らーめん', meaning: 'Mì Ramen', category: 'food' },
  { front: '天ぷら', reading: 'てんぷら', meaning: 'Món Tempura chiên giòn', category: 'food' },
  { front: '味噌汁', reading: 'みそしる', meaning: 'Canh miso', category: 'food' },

  // Giao thông, Địa điểm & Thành phố
  { front: '駅', reading: 'えき', meaning: 'Nhà ga tàu điện', category: 'transport' },
  { front: '電車', reading: 'でんしゃ', meaning: 'Tàu điện', category: 'transport' },
  { front: '地下鉄', reading: 'ちかてつ', meaning: 'Tàu điện ngầm', category: 'transport' },
  { front: '新幹線', reading: 'しんかんせん', meaning: 'Tàu cao tốc Shinkansen', category: 'transport' },
  { front: 'バス', reading: 'ばす', meaning: 'Xe buýt', category: 'transport' },
  { front: 'タクシー', reading: 'たくしー', meaning: 'Xe taxi', category: 'transport' },
  { front: '飛行機', reading: 'ひこうき', meaning: 'Máy bay', category: 'transport' },
  { front: '船', reading: 'ふね', meaning: 'Tàu thủy, thuyền', category: 'transport' },
  { front: '空港', reading: 'くうこう', meaning: 'Sân bay', category: 'places' },
  { front: '病院', reading: 'びょういん', meaning: 'Bệnh viện', category: 'places' },
  { front: '郵便局', reading: 'ゆうびんきょく', meaning: 'Bưu điện', category: 'places' },
  { front: '銀行', reading: 'ぎんこう', meaning: 'Ngân hàng', category: 'places' },
  { front: '公園', reading: 'こうえん', meaning: 'Công viên', category: 'places' },
  { front: '交番', reading: 'こうばん', meaning: 'Đồn cảnh sát', category: 'places' },
  { front: '神社', reading: 'じんじゃ', meaning: 'Đền Thần đạo', category: 'culture' },
  { front: 'お寺', reading: 'おてら', meaning: 'Chùa Phật giáo', category: 'culture' },
  { front: 'コンビニ', reading: 'こんびに', meaning: 'Cửa hàng tiện lợi Konbini', category: 'places' },
  { front: 'スーパー', reading: 'すーぱー', meaning: 'Siêu thị', category: 'places' },

  // Thời gian, Thời tiết & Tự nhiên
  { front: '今日', reading: 'きょう', meaning: 'Hôm nay', category: 'time' },
  { front: '明日', reading: 'あした', meaning: 'Ngày mai', category: 'time' },
  { front: '昨日', reading: 'きのう', meaning: 'Hôm qua', category: 'time' },
  { front: '今週', reading: 'こんしゅう', meaning: 'Tuần này', category: 'time' },
  { front: '来週', reading: 'らいしゅう', meaning: 'Tuần tới', category: 'time' },
  { front: '今月', reading: 'こんげつ', meaning: 'Tháng này', category: 'time' },
  { front: '来年', reading: 'らいねん', meaning: 'Năm sau', category: 'time' },
  { front: '春', reading: 'はる', meaning: 'Mùa xuân', category: 'nature' },
  { front: '夏', reading: 'なつ', meaning: 'Mùa hè', category: 'nature' },
  { front: '秋', reading: 'あき', meaning: 'Mùa thu', category: 'nature' },
  { front: '冬', reading: 'ふゆ', meaning: 'Mùa đông', category: 'nature' },
  { front: '天気', reading: 'てんき', meaning: 'Thời tiết', category: 'nature' },
  { front: '雨', reading: 'あめ', meaning: 'Cơn mưa', category: 'nature' },
  { front: '雪', reading: 'ゆき', meaning: 'Tuyết rơi', category: 'nature' },
  { front: '桜', reading: 'さくら', meaning: 'Hoa anh đào Sakura', category: 'nature' },
  { front: '富士山', reading: 'ふじさん', meaning: 'Núi Phú Sĩ', category: 'nature' },

  // Động từ hành vi then chốt
  { front: '行く', reading: 'いく', meaning: 'Đi', category: 'action' },
  { front: '来る', reading: 'くる', meaning: 'Đến', category: 'action' },
  { front: '帰る', reading: 'かえる', meaning: 'Về nhà', category: 'action' },
  { front: '食べる', reading: 'たべる', meaning: 'Ăn', category: 'action' },
  { front: '飲む', reading: 'のむ', meaning: 'Uống', category: 'action' },
  { front: '見る', reading: 'みる', meaning: 'Xem, nhìn', category: 'action' },
  { front: '聞く', reading: 'きく', meaning: 'Nghe, hỏi', category: 'action' },
  { front: '読む', reading: 'よむ', meaning: 'Đọc sách', category: 'action' },
  { front: '書く', reading: 'かく', meaning: 'Viết thư, vẽ tranh', category: 'action' },
  { front: '話す', reading: 'はなす', meaning: 'Nói chuyện', category: 'action' },
  { front: '勉強する', reading: 'べんきょうする', meaning: 'Học tập', category: 'action' },
  { front: '仕事する', reading: 'しごとする', meaning: 'Làm việc', category: 'action' },
  { front: '買い物する', reading: 'かいものする', meaning: 'Mua sắm', category: 'action' },
  { front: '散歩する', reading: 'さんぽする', meaning: 'Đi dạo', category: 'action' },
  { front: '旅行する', reading: 'りょこうする', meaning: 'Đi du lịch', category: 'action' },
];

export const EXPANDED_IMMERSION_TOPICS = [
  { keyword: 'こんにちは', topic: 'Chào hỏi văn phòng Tokyo', level: 'N5', situation: 'Gặp gỡ đồng nghiệp lúc 12h trưa' },
  { keyword: 'ありがとう', topic: 'Lời cảm ơn chân thành', level: 'N5', situation: 'Cảm ơn khi được giúp đỡ dự án' },
  { keyword: 'すみません', topic: 'Gọi nhân viên tiệm ăn', level: 'N5', situation: 'Xin lỗi và gọi món thêm ramen' },
  { keyword: '駅', topic: 'Chỉ đường tại nhà ga Shinjuku', level: 'N5', situation: 'Hỏi hướng ra cửa Tây ga tàu' },
  { keyword: '電車', topic: 'Thông báo trên tuyến Yamanote', level: 'N5', situation: 'Thông báo tàu sắp dừng tại ga Tokyo' },
  { keyword: 'ご飯', topic: 'Bữa cơm tối gia đình', level: 'N5', situation: 'Chúc ngon miệng và cảm ơn sau bữa ăn' },
  { keyword: '勉強', topic: 'Ôn thi JLPT cùng bạn', level: 'N5', situation: 'Thảo luận ngữ pháp khó trong giờ nghỉ' },
  { keyword: '友達', topic: 'Hẹn hò cuối tuần', level: 'N5', situation: 'Lên kế hoạch đi xem triển lãm nghệ thuật' },
  { keyword: '仕事', topic: 'Báo cáo tiến độ cho sếp', level: 'N4', situation: 'Báo cáo hoàn thành công việc trước hạn' },
  { keyword: '天気', topic: 'Dự báo ngắm hoa Hanami', level: 'N5', situation: 'Dự báo thời tiết cuối tuần nắng ấm' },
  { keyword: '病院', topic: 'Khai bệnh tại phòng khám', level: 'N4', situation: 'Bác sĩ hỏi về thời gian bắt đầu sốt' },
  { keyword: '買い物', topic: 'Tính tiền tại Konbini', level: 'N5', situation: 'Hỏi thẻ tích điểm và từ chối túi nhựa' },
  { keyword: '旅行', topic: 'Nhận phòng khách sạn Kyoto', level: 'N4', situation: 'Xác nhận đặt phòng và giờ ăn sáng' },
  { keyword: '電話', topic: 'Ứng xử nghe điện thoại công sở', level: 'N4', situation: 'Nhận cuộc gọi và chuyển máy cho cấp trên' },
  { keyword: '予約', topic: 'Đặt chỗ tiệm nướng Yakiniku', level: 'N4', situation: 'Đặt bàn 4 người vào tối thứ Bảy' },
  { keyword: '新幹線', topic: 'Mua vé tàu cao tốc Nozomi', level: 'N4', situation: 'Chọn ghế sát cửa sổ đi Shin-Osaka' },
  { keyword: '面接', topic: 'Phỏng vấn kỹ sư công nghệ', level: 'N3', situation: 'Trình bày lý do muốn làm việc tại Nhật' },
  { keyword: '引越し', topic: 'Chuyển nhà và chào hàng xóm', level: 'N4', situation: 'Tặng món quà nhỏ ra mắt hàng xóm mới' },
  { keyword: '温泉', topic: 'Quy tắc tắm suối nước nóng', level: 'N4', situation: 'Nhân viên hướng dẫn tắm tráng trước khi xuống bể' },
  { keyword: '桜', topic: 'Lễ hội hoa anh đào Ueno', level: 'N5', situation: 'Cùng đồng nghiệp trải thảm ngắm hoa' },
  { keyword: '残業', topic: 'Làm thêm giờ tại công ty', level: 'N3', situation: 'Xin phép ở lại hoàn thiện tài liệu hợp đồng' },
  { keyword: '台風', topic: 'Cảnh báo bão đổ bộ Kanto', level: 'N3', situation: 'Bản tin đài NHK khuyên người dân ở yên trong nhà' },
  { keyword: '地震', topic: 'Diễn tập phòng chống thiên tai', level: 'N4', situation: 'Hướng dẫn di tản an toàn khi có rung chấn' },
  { keyword: '敬語', topic: 'Giao tiếp đối tác thương mại', level: 'N2', situation: 'Sử dụng kính ngữ Sonkeigo chào đón khách quý' },
  { keyword: '契約', topic: 'Ký kết hợp đồng phát triển web', level: 'N2', situation: 'Thống nhất điều khoản bàn giao bản quyền phần mềm' },
];

export const EXPANDED_OXFORD_WORDS = [
  'ubiquitous', 'paradigm', 'empirical', 'pragmatic', 'juxtaposition',
  'corroborate', 'mitigate', 'disseminate', 'meticulous', 'anomaly',
  'ephemeral', 'lucid', 'esoteric', 'pervasive', 'tenacious',
  'proliferation', 'exacerbate', 'retention', 'cognitive', 'pedagogy',
  'resilient', 'comprehensive', 'synthesize', 'formulate', 'evaluate',
  'scrutinize', 'profound', 'intricate', 'preliminary', 'concurrent',
  'indigenous', 'substantiate', 'circumvent', 'ambiguous', 'lucrative',
  'deteriorate', 'facilitate', 'inevitable', 'prevalent', 'reluctant',
  'substantial', 'unprecedented', 'vulnerable', 'arbitrary', 'coherent',
  'diminish', 'feasible', 'hierarchy', 'plausible', 'spontaneous',
  'advocate', 'aesthetic', 'alleviate', 'altruistic', 'amorphous',
  'anachronism', 'analogy', 'anticipate', 'apathy', 'articulate',
  'augment', 'autonomous', 'benevolent', 'bias', 'candid',
  'catalyst', 'chronic', 'chronological', 'clarify', 'coincide',
  'collaborate', 'commensurate', 'compatible', 'compensate', 'compile',
  'complement', 'concede', 'concise', 'condone', 'conducive',
  'conform', 'conjecture', 'consensus', 'constitute', 'constrain',
  'contemplate', 'contend', 'contradict', 'convene', 'converge',
  'convey', 'conviction', 'cumulative', 'curtail', 'daunting',
  'debilitate', 'deduce', 'defer', 'deficient', 'definitive',
  'degrade', 'delineate', 'demonstrate', 'denote', 'depict',
  'deprecate', 'derive', 'detrimental', 'deviate', 'devise',
  'diffuse', 'digress', 'discreet', 'discrete', 'discriminating',
  'disdain', 'disillusion', 'dispassionate', 'disperse', 'disposition',
  'disproportionate', 'dispute', 'disregard', 'dissent', 'distort',
  'divergent', 'diversity', 'dogmatic', 'drastic', 'dubious'
];

export const EXPANDED_PUBMED_TOPICS = [
  { topic: 'Japanese Cognition & Neuroscience', query: 'japanese language cognition memory neuroscience' },
  { topic: 'Spaced Repetition & Cognitive Load', query: 'spaced repetition memory retrieval practice cognitive load' },
  { topic: 'Tokyo Pitch Accent Phonology', query: 'japanese pitch accent phonology bilingual speech perception' },
  { topic: 'Bilingual Brain & fMRI Studies', query: 'kanji reading neuroscience brain activation fMRI' },
  { topic: 'Memory Consolidation & Forgetting Curve', query: 'memory consolidation ebbinghaus retention interval' },
  { topic: 'Second Language Acquisition & Working Memory', query: 'second language acquisition working memory executive function' },
  { topic: 'Neuroplasticity & Auditory Processing', query: 'neuroplasticity auditory cortical language learning' },
  { topic: 'Clinical Japanese Medical Terminology', query: 'japanese medical terminology clinical healthcare communication' },
  { topic: 'Sleep & Memory Consolidation', query: 'sleep memory consolidation synaptic plasticity spaced practice' },
  { topic: 'Desirable Difficulties & Retrieval Effort', query: 'desirable difficulties testing effect retrieval practice bjork' },
];
